[2022-11-18T00:53:50.361+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2022-11-18T00:53:50.390+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info scheduled__2022-11-17T00:00:00+00:00 [queued]>
[2022-11-18T00:53:50.391+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T00:53:50.392+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-18T00:53:50.393+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T00:53:50.416+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_es_info> on 2022-11-17 00:00:00+00:00
[2022-11-18T00:53:50.433+0000] {standard_task_runner.py:55} INFO - Started process 325 to run task
[2022-11-18T00:53:50.443+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'elastic_dag', 'print_es_info', 'scheduled__2022-11-17T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/elastic_dag.py', '--cfg-path', '/tmp/tmprnfp26cf']
[2022-11-18T00:53:50.448+0000] {standard_task_runner.py:83} INFO - Job 155: Subtask print_es_info
[2022-11-18T00:53:50.603+0000] {task_command.py:376} INFO - Running <TaskInstance: elastic_dag.print_es_info scheduled__2022-11-17T00:00:00+00:00 [running]> on host 9acdffb18527
[2022-11-18T00:53:50.744+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2022-11-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-17T00:00:00+00:00
[2022-11-18T00:53:50.748+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/elastic_dag.py", line 9, in _print_es_info
    print(hook.info())
TypeError: info() missing 1 required positional argument: 'self'
[2022-11-18T00:53:50.769+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=elastic_dag, task_id=print_es_info, execution_date=20221117T000000, start_date=20221118T005350, end_date=20221118T005350
[2022-11-18T00:53:50.794+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 155 for task print_es_info (info() missing 1 required positional argument: 'self'; 325)
[2022-11-18T00:53:50.853+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-18T00:53:50.920+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
